version: "3.8"

services:
  - type: web
    name: klipy-clipboard-sync
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
    domains:
      - klipy-clipboard-sync.onrender.com

    # Health check
    healthCheckPath: /

    # Auto-deploy on git push
    autoDeploy: true

    # Environment variables that need to be set in Render dashboard:
    # (Add these manually in the Render dashboard)
    # - Any additional environment variables your app needs

    # Build settings
    buildFilter:
      paths:
        - "**"
      ignoredPaths:
        - "test-*"
        - "*.md"
        - ".gitignore"

    # Resource limits (free tier)
    disk: 1GB

    # Logs retention
    logRetention: 7 # days

# Optional: If you need a database, uncomment and configure
# databases:
#   - name: klipy-db
#     databaseName: klipy
#     user: klipy_user
#     plan: free

# Optional: If you need Redis for caching, uncomment
# services:
#   - type: redis
#     name: klipy-redis
#     plan: free
#     maxmemoryPolicy: allkeys-lru
